/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Titanium SDK
 * Copyright TiDev, Inc. 04/07/2022-Present
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 */
package com.accusolutions.root;

import com.scottyab.rootbeer.RootBeer;

import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;

import org.appcelerator.titanium.TiApplication;
import org.appcelerator.kroll.common.TiConfig;


@Kroll.module(name = "AccuRoot", id = "com.accusolutions.root")
public class AccuRootModule extends KrollModule {

    // Standard Debugging variables
    private static final String LCAT = "AccuRootModule";
    private static final boolean DBG = TiConfig.LOGD;
    private final RootBeer rootBeer;
    private boolean shouldCrash = false;

    public AccuRootModule() {
        super();
        rootBeer = new RootBeer(TiApplication.getAppCurrentActivity());
    }

    @Kroll.onAppCreate
    public static void onAppCreate(TiApplication app) {
    }

    // Methods
    @Kroll.method
    public boolean isTamperedWith() {
        boolean isTamperedWith = rootBeer.isRooted();
        if (this.shouldCrash && isTamperedWith) {
            System.exit(0);
        }
        return isTamperedWith;
    }

    // Properties
    @Kroll.getProperty
    public boolean getShouldCrash() {
        return shouldCrash;
    }


    @Kroll.setProperty
    public void setExampleProp(boolean shouldCrash) {
        this.shouldCrash = shouldCrash;
    }
}

